# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'week5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for week5
  
  pod 'Alamofire', '~> 5.2'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'MaterialComponents/BottomSheet'

end
